apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-reg-deployment
  labels:
    app: userregister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userregister
  template:
    metadata:
      labels:
        app: userregister
    spec:
      containers:
      - name: userregister
        image: userreg.azurecr.io/userreg:latest
        ports:
        - containerPort: 8080